repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        exclude: ^2020/.*$
        args:
          - --score=n
          - -d fixme
          - -d missing-module-docstring
          - -d missing-function-docstring
          - -d import-error
          - -d wrong-import-order
          - -d logging-fstring-interpolation # see https://github.com/PyCQA/pylint/issues/1788
          - -d invalid-name
          - -d redefined-outer-name
        require_serial: false
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]
